### ISSUE TITLE
Identify a subset of DCP/1 data sets

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/dcp-prototype#174]
[**March 20 Demo Action Items**](https://docs.google.com/presentation/d/1nY4PXzOEs8euFEAlp2dHxB5dMZTZLSuinXzOo_eR7Ig/edit#slide=id.p4)

 Identify a subset of DCP/1 data sets [cXg matrices] to be "migrated" [and include project metadata]

---

**References**:
[All DCP/1 Data Sets](https://docs.google.com/spreadsheets/d/1Qtbut2-yL2i7mPfN6gd154i255BzteX0gCTG9kPHOwc/edit#gid=199402071)

Related slack conversations: [[1]](https://chanzuckerbergteam.slack.com/archives/CS66X37CZ/p1583173661008300?thread_ts=1582933161.032300&cid=CS66X37CZ) and [[2]](https://chanzuckerbergteam.slack.com/archives/CS66X37CZ/p1583186542015500)

**Comment by jychien** [comment]
**Document containing details:**
https://docs.google.com/spreadsheets/d/1Qtbut2-yL2i7mPfN6gd154i255BzteX0gCTG9kPHOwc/edit?usp=sharing

**CONTRIBUTOR MATRIX & ANNOTATION**:
This tab lists the DCP1 projects that have had its corresponding public matrices and metadata assessed for the availability of dimensionality reduction embeddings. The heuristics for prioritizing projects is: human > mouse, simpler studies > complex studies, and has annotations > does not have annotation ([slack comment](https://cziscience.slack.com/archives/CS66X37CZ/p1583174130008500?thread_ts=1582933161.032300&cid=CS66X37CZ))

**SUMMARY**:
- Majority of projects do not have embeddings available in the public domain.
- **_Spatio-temporal immune zonation of the human kidney_**: This data is currently being hosted at https://www.kidneycellatlas.org/, where a cellxgene interactive viewer is available for subsets of the data and the h5ad file is downloadable. 
- **_Structural Remodeling of the Human Colonic Mesenchyme in Inflammatory Bowel Disease_**: Data generators were previously contacted during UX exercise, and they provided tSNE embeddings and cluster annotation. This would need to be mapped to the contributor matrix. Files are have been uploaded to a [google drive](https://drive.google.com/open?id=1IjZIBCwJhNSoGITmxayemR8raQynqvAi).

**Comment by brianraymor** [comment]
Pending actions to complete review and close - @jahilton wrote:

 _that's on me and @ambrosejcarr to look at what does/doesn't make sense to migrate_

**Comment by jahilton** [comment]
I've gone through and marked each DCP dataset with a priority ([Column A](https://docs.google.com/spreadsheets/d/1Qtbut2-yL2i7mPfN6gd154i255BzteX0gCTG9kPHOwc/edit#gid=199402071)). Priority based on human, healthy/reference tissue, Seed Network members.
I see 7 as priority to migrate prior to 'going live', then list the others in order or priority. There are some at the bottom that I'd like to run by Seed Network members to understand the value of the dataset before placing it in the priority list.

Curious what @ambrosejcarr 's thoughts are.

**Comment by jahilton** [comment]
As our team will focus on Seed Network data, and that's the only criteria needed to determine datasets to migrate, so previous comments about prioritizing are irrelevant now.

We will migrate the 1 Seed network project & the 8 pilot projects:
snRNA retina (Chen) - 9c20a245-f2c0-43ae-82c9-2232ec6b594f
HDCA (Linnarsson/Lonnerberg) - 008e40e8-66ae-43bb-951c-c073a2fa6774
Early Human Diabetic Nephropathy (Humphreys/Wilson) - 577c946d-6de5-4b55-a854-cd3fde40bff2
Kidney (Humphreys) - 027c51c6-0719-469f-a7f5-640fe57cbece
T cell activation (Sims/Farber) - 4a95101c-9ffc-4f30-a809-f04518a23803
scRNA-Seq comparison (Pott/Basu) - a9c022b4-c771-4468-b769-cabcf9738de3
Ischaemic sensitivity (Meyer/Stegle/etal) - c4077b3c-5c98-4d26-a614-246d12c2e5d7
Cell hashing (Satija/Smibert) - f81efc03-9f56-4354-aabb-6ce819c3d414
Bone marrow (Amit) - a29952d9-925e-40f4-8a1c-274f118f1f51

After those are migrated, we will evaluate the required and consider additional DCP datasets, if bandwidth allows.
