### ISSUE TITLE
Audit fastq sequence file lengths for DCP1 projects

### ISSUE THREAD

**Issue by jychien** [chanzuckerberg/dcp-prototype#208]
Make sure that sequence read lengths in the metadata are as to be expected for fastq files.
For 10x 3' v2, the optimum lengths are:
- Read1: 26 bp (16 cell barcode, 10 UMI)
- Read2: 98 bp
- Index: 8 bp

For 10x 3' v3, the optimum lengths are:
- Read1: 28 bp (16 cell barcode, 12 UMI)
- Read2: 91 bp
- Index: 8 bp

Record all sequence lengths for other assays.

**Comment by jychien** [comment]
**Documentation**: https://docs.google.com/spreadsheets/d/1Qtbut2-yL2i7mPfN6gd154i255BzteX0gCTG9kPHOwc/edit?usp=sharing

Looked at `sequence_file.read_length` for each assay per project by assessing the wrangler spreadsheets. The lengths are listed as _Read1 length in metadata_, _Read2 length in metadata_, _Index1 length in metadata_, and _Index2 length in metadata_ in the documentation.

For projects or assay with `sequence_file.read_length` omitted from the wrangler spreadsheet, the value is entered as "not listed" on the documentation.

@jahilton

**Comment by jahilton** [comment]
Super helpful!
