### ISSUE TITLE
Fix deep linking

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/dcp-prototype#215]
Deep links (e.g. to a project page) are broken and routes you to the home/projects list page.

STR:
Visit https://browser.dev.single-cell.czi.technology/project?id=005d611a-14d5-4fbf-846e-571a1f874f70

AC:
https://browser.dev.single-cell.czi.technology/project?id=005d611a-14d5-4fbf-846e-571a1f874f70 renders the correct project page

**Comment by Bento007** [comment]
@colinmegill this might help you https://github.com/chanzuckerberg/dcp-prototype/issues/217#issuecomment-604743797
