### ISSUE TITLE
Fix blank page bug

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/dcp-prototype#216]
Frequently, when you navigate away from a project page (1. by pressing the back button, 2. clicking the CZI logo in the top left corner), a blank page will render.

STR:
Visit https://browser.dev.single-cell.czi.technology/project?id=005d611a-14d5-4fbf-846e-571a1f874f70
Press "back" or the click the CZI logo
See blank page

AC:
Blank pages don't render while navigating around the site

**Comment by mweiden** [comment]
Can't reproduce. Probably fixed as part of Trent and Calvin's other fixes.
