### ISSUE TITLE
Fix page refresh

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/dcp-prototype#217]
When the page is refreshed on a project page, you're returned to the home/projects list page.

STR:
Visit https://browser.dev.single-cell.czi.technology/project?id=005d611a-14d5-4fbf-846e-571a1f874f70
Refresh the page

AC:
Refreshing the page on any page reloads the same page

**Comment by Bento007** [comment]
relates to #215

**Comment by Bento007** [comment]
From what I've read this is an issue with How AWS S3 and AWS Cloudfront are configured. The way it's currently configured all redirect links are broken and return to "index.html". The S3 bucket needs to be public and hosted out of the s3 bucket and Cloudfront needs to use the s3 bucket domain as a resource origin. Unfortunately this goes against our best practices of having private s3 and results in two different site URLS. One URL for cloud front and one URL for the S3 bucket.

More info can be found [here](https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront/)
