### ISSUE TITLE
Authentication Bar Disappears on Frontend header

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/dcp-prototype#221]
# Problem
In the browser, when you login to the front end and navigate to a different page, the authentication bar disappears. In the browser console you can see there was an authorization error talking to auth0. Going into the auth0 Console under logs you can see:

> **Type**: Failed Silent Auth
> **Description**: 
> The specified redirect_uri 'https://browser.dev.single-cell.czi.technology/' does not have a registered origin.

The Allowed Web Origins is set to `https://browser.dev.single-cell.czi.technology/`.

**Comment by mweiden** [comment]
Seems to work now!
