### ISSUE TITLE
Build artifact

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/dcp-prototype#5]
- [ ] Move ledger files to artifact bucket
- [ ] Automated build of artifact matching jsonschema
    - [ ] artifact builder script packaged in docker
    - [ ] aws infra to run artifact builder docker image

**Comment by brianraymor** [comment]
Per the discussion at the DCP/2 Leads meeting on Jan 30, we will be more precise in how we refer to flattened metadata:

* _Software readable metadata_ for files such as project.tsv or files.tsv consumed in the browser
* _Metadata downloadable **blob**_  for the full metadata download file

**Comment by maniarathi** [comment]
@ambrosejcarr Is this still relevant? The latter part of the ticket (metadata for the browser) is handled by extraction from the artifact. How about the metadata downloadable blob?

**Comment by parthshahva** [comment]
@maniarathi this ticket has nothing to do with the browser. This is part of the automation of artifact building. I've updated the ticket and assigned myself

**Comment by maniarathi** [comment]
Closing this ticket as part of a cleanup of this repo's open issues given that a new roadmap will soon be deployed.
