### ISSUE TITLE
Populate Artifact with entirety of DCP 1.0 data.

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/dcp-prototype#86]
In order to meet the requirements for the March 20th demo, for each of the datasets in DCP 1.0, we will need to ensure that the metadata required for the artifact is pulled out and flattened into JSON.

Tasks:
1) Hunting down per-project matrices for each project.
2) Migrating the matrices to use metadata fields names that are a part of the 2.0 metadata schema.
3) Generating the JSON with the required metadata fields that will be needed to make it a part of the Artifact.
4) Ensuring all appropriate files are copied to the right locations.

Related Work/Links:
- [DCP Experimental Diagrams](https://www.draw.io/#G1i1YIjxBQ6gkX3L3PO7GNwYGjpWwgEZNJ): this document tells you how to populate the BiosamplePrep entity based on the type of dataset
- [DCP Project to Biosample Prep Category Document](https://docs.google.com/spreadsheets/d/1u6T37eij_Qm0cY2eyKbuAvJhZfGsIQUHDMFhczDEwLA/edit#gid=0): this document tells you which type of dataset each dataset is from DCP 1.0.
- [DCP 2.0 Metadata Schema v1.1.0](https://www.draw.io/#G19Tm2KJ53uJfUkjvI5XqOaps1-ltYF_ID)

**Comment by parthshahva** [comment]
Issues found so far with the initial load of the pancreas dataset
1) 5087 instead of 5088 expected sequence files
2) Not seeing an expression file (loom file) or any associated process in the db
3) There is no process connecting sequence file, alignment protocol, and analysis files. I believe the alignment protocol should be hardcoded

**Comment by maniarathi** [comment]
1. This is one is stumping me. I haven't been able to reproduce it in toy runs and I also see 5088 files in S3 both of FASTQ type and of `sequence_file.json` type. May just run again to see if I can reproduce.
2. This is expected. Will populate this last once the re-run the migration.
3. Fixed this bug and will now re-run.

**Comment by maniarathi** [comment]
Will also pipe the logs to file so that I can figure out whether all 5088 files were processed based on my logging.

**Comment by parthshahva** [comment]
Potential issue found with contributors
Here are the contributor entries for the pancreas project. However, one of them is missing a contributor role ontology. This makes it difficult to determine which is the main contributor vs contributing/wrangler contributors.
```
HCA-Contributor-0e7def4c-fe20-45f4-a15e-a600cfbde5c9 | Martin, Enge   | martin.enge@gmail.com |                    | false                     |                                             | Bioengineering, Stanford University, James H. Clark Center, 318 Campus Drive,, Stanford, CA, USA | USA     |                           |                     | 2020-02-14 16:47:37.629494+00 | 2020-02-14 16:47:37.629494+00
 HCA-Contributor-f1177dc1-cc4d-4215-bd36-df4fd99b9847 | Laura,,Huerta  | lauhuema@ebi.ac.uk    |                    | false                     | Molecular Atlas                             | Wellcome Trust Genome Campus, Cambridge UK                                                       | UK      | EFO:0009737               | 0000-0002-8748-599X | 2020-02-14 16:47:37.629494+00 | 2020-02-14 16:47:37.629494+00
 HCA-Contributor-9fbcb5a9-7a27-4c28-bed7-86ffc6501b44 | Matthew,,Green | hewgreen@ebi.ac.uk    | (+44) 122-349-4444 | false                     | Human Cell Atlas Data Coordination Platform | Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SD                                        | UK      | EFO:0009737               | 0000-0003-2771-9894 | 2020-02-14 16:47:37.629494+00 | 2020-02-14 16:47:37.629494+00
```

**Comment by parthshahva** [comment]
Here is a potential issue with the contributors table. One of the contributors is missing a contributor role ontology. This makes it difficult to determine who the main contributor is vs contributing/wrangler contributors
```
HCA-Contributor-0e7def4c-fe20-45f4-a15e-a600cfbde5c9 | Martin, Enge   | martin.enge@gmail.com |                    | false                     |                                             | Bioengineering, Stanford University, James H. Clark Center, 318 Campus Drive,, Stanford, CA, USA | USA     |                           |                     | 2020-02-14 16:47:37.629494+00 | 2020-02-14 16:47:37.629494+00
 HCA-Contributor-f1177dc1-cc4d-4215-bd36-df4fd99b9847 | Laura,,Huerta  | lauhuema@ebi.ac.uk    |                    | false                     | Molecular Atlas                             | Wellcome Trust Genome Campus, Cambridge UK                                                       | UK      | EFO:0009737               | 0000-0002-8748-599X | 2020-02-14 16:47:37.629494+00 | 2020-02-14 16:47:37.629494+00
 HCA-Contributor-9fbcb5a9-7a27-4c28-bed7-86ffc6501b44 | Matthew,,Green | hewgreen@ebi.ac.uk    | (+44) 122-349-4444 | false                     | Human Cell Atlas Data Coordination Platform | Wellcome Trust Genome Campus, Hinxton, Cambridge CB10 1SD                                        | UK      | EFO:0009737               | 0000-0003-2771-9894 | 2020-02-14 16:47:37.629494+00 | 2020-02-14 16:47:37.629494+00
```

**Comment by parthshahva** [comment]
Another possible issue noted. For this project, there are 2544 biosample_preps but only one library_prep_protocol and one library. I would expect to see 2544 biosample_preps, 1 library_prep_protocol, and 2544 libraries to maintain the relationship between the paired sequence files and the biosample prep via the library. Confirmed with @mckinsel

**Comment by maniarathi** [comment]
Contributor issue: That information does not exist for Martin, Enge for that dataset. Double checked directly in the DCP 1.0 metadata file.

Re: Libraries: I stand by what I said in the dcp-2 channel. As the UML stands today, the Library entity contains only a reference to a Project entity, of which there is one. You will find that there are 2544 entities in the BiosamplePrepLibraryLibraryPrepProtocolProcessJoin table which links together a biosample prep entity, a library prep protocol entity, and a library entity. It seems to me that there is a mistake in the UML diagram which does not ensure that the Library entity is composed of a foreign key reference to a Biosample Prep as well. This used to be represented in v1.0.0, but it is not v.1.1.0, thus the first migration of the data used to have 2544 library entities, but using v1.1.0, it has one library entity. Will discuss further on Tuesday.

**Comment by maniarathi** [comment]
Closing this ticket as part of a cleanup of this repo's open issues given that a new roadmap will soon be deployed.
